### ISSUE TITLE
why are we stochastically docking to chain A vs chain B when the crystal ligand exists in both chains?

### ISSUE THREAD

**Issue by JenkeScheen** [choderalab/covid-moonshot-ml#124]
I'm still running into this issue (on main), was this unresolved or is it resurfacing? 

Are there any sets we can test this on?

**Comment by apayne97** [comment]
The issue arises when there are ligands in both chains. After discussing with Jenke, he used this source directory:
`/lila/data/chodera/asap-datasets/full_frag_prepped_dus_seqres/*/prepped_receptor.oedu`

I will check to see if that was before or after we implemented the change in #103

**Comment by apayne97** [comment]
This was before!
``
~/asap-datasets/full_frag_prepped_dus_seqres$ ll
total 284K
kaminowb jclab 4.0K Oct 26 11:33 Mpro-P0008_0A_ERI-UCB-ce40166b-17
```

**Comment by JenkeScheen** [comment]
Nice, thanks a lot for checking!
