### ISSUE TITLE
Robustify RMSD calculation protocol (re-running with POSIT broke the RMSD calculation again)

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#30]
@kaminow can you add here what you've done to calculate RMSD, what's worked, what hasn't?

# Methods

## 1) Basic OpenEye
`oechem.OERMSD(ref, mobile)` where ref and mobile are `OEMolBase` objects
- fails (returns -1) when the states of the two ligands aren't identical

## 2) Basic mdtraj
- fails (i.e. doesn't run at all) if n_atoms isn't identical
- will run if your atoms are out of order but it will not try to correct them

## 3) OpenEye from PDB
https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/covid_moonshot_ml/data/openeye.py#L59
a. load from PDB and SDF files
b. delete hydrogens from PDB file
c. run `1)`
- again, fails if atom typing is not identical

## 4) OpenEye manual RMSD calculation (what @kaminow mentions below)
https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/scripts/hallucinate_fragalysis.py#L288-L309

**Comment by kaminow** [comment]
I think the code that I added here should address this:
https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/scripts/hallucinate_fragalysis.py#L288-L309
it's ugly but it should be fairly robust

**Comment by apayne97** [comment]
The code makes sense to me, although does feel very....manual. It still fails if the bond orders aren't the same, right? Which shouldn't be a problem in this case but maybe for use in the future we can add this?
https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OEApplyStateFromRef.html

**Comment by apayne97** [comment]
Also, I wonder if in the hallucinate_fragalysis script it would be good to save the sdf files after canonicalizing them? so that in the future they should be the same?

**Comment by kaminow** [comment]
I can experiment with it, but per [the docs](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OECanonicalOrderAtoms.html), the function doesn't actually change anything about the atoms themselves, just the order in which they're visited when iterating through

**Comment by apayne97** [comment]
> I can experiment with it, but per [the docs](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemFunctions/OECanonicalOrderAtoms.html), the function doesn't actually change anything about the atoms themselves, just the order in which they're visited when iterating through

Oh. nvm then about saving after canonicalizing.

**Comment by apayne97** [comment]
This has been implemented in `docking.docking.run_docking_oe` but will be moved to docking.analysis
