### ISSUE TITLE
standardize a way to assess "good" predictions

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#32]
Related to #31 

I have made an implementation here but if we use a common function to do this that will improve confidence that we're using the same metrics across tasks:

https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/covid_moonshot_ml/docking/analysis.py#L143

**Comment by kaminow** [comment]
I think using `numpy.lexsort` might give us the desired behavior. that way we can rank by all four values (POSIT prob, RMSD, Chemgauss score, and MCSS rank). we'll probably have to negate the POSIT prob though so that we can sort all four keys in the same direction

**Comment by apayne97** [comment]
Making a POSIT_R = -POSIT column makes sense.

I was thinking we would want to filter (not just sort) by some of the values? Or we can generate like a composite scaled score of some kind.

For example in the case that:
Complex 1
- POSIT = 0.9
- RMSD = 6
- Chemgauss4 = 4

Complex 2
- POSIT = 0.8889
- RMSD = 1.2
- Chemgauss4 = -15

Just sorting them in order would return Complex 1, but probably Complex 2 is a better choice. Right?

**Comment by apayne97** [comment]
I think he had originally said to pick the score with the best Chemgauss4 score that has an RMSD of < 2Å?
Also this is basically https://github.com/choderalab/covid-moonshot-ml/issues/31

**Comment by kaminow** [comment]
ah ok, in that case I think your idea here:
https://github.com/choderalab/covid-moonshot-ml/blob/hallucinate-fragalysis/covid_moonshot_ml/docking/analysis.py#L227-L228
is a good plan

**Comment by apayne97** [comment]
I think I've already done a good enough job at this for our purposes in the original place I posted it above
