### ISSUE TITLE
Add ligand-based filtering to only dock ligands of a certain type

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#35]
# To-Do
- [x] figure out a way to filter by certain ligand types (make a yaml file mapping a name to a particular SMARTS filter)
- [x] implement filtering step in the docking script

**Comment by apayne97** [comment]
John suggests using the SMARTs strings contained in this CSV file: https://github.com/FoldingAtHome/covid-moonshot/blob/master/synthetic-enumeration/sprint-12/annotations/annotations.csv

**Comment by JenkeScheen** [comment]
Following discussion with @apayne97 I made a prototype for this functionality here: https://github.com/choderalab/covid-moonshot-ml/commit/5d2be92c053a39840f675a91fde699ffe6dd5bc1; apologies for committing on `hallucinate_fragalysis` directly, will carry future iterations on the feature branch `add-lig-based_filtering`. The committed files are independent so there shouldn't be any issues.

The function ingests a CSV with SMARTS queries and uses them to filter an input file (space-separated for now, I figured [the sprint 12 compounds](https://github.com/FoldingAtHome/covid-moonshot/blob/master/synthetic-enumeration/sprint-12/docked/sprint-12-compounds.smi) would be a good use-case). 

Some Qs so I can finalise this, mostly @apayne97 and @kaminow:
- is path-based I/O ok or is another way desired? If so please point me to an example
- where would you like this function implemented?
- is there need for the inverse function as well? i.e. if query SMARTS is found, remove the cpd from docking input?
- I wasn't sure what the hashtags represent in @jchodera's [SMARTS queries file example](https://github.com/FoldingAtHome/covid-moonshot/blob/master/synthetic-enumeration/sprint-12/annotations/annotations.csv) represented but I'm assuming they're used to enable/disable filters. With the hashtags SMARTS parsing by OE fails of course, so I set a flag to either ignore the commented SMARTS entries or to include all of them by removing the hashtag.

**Comment by JenkeScheen** [comment]
pushed to correct feature branch now, see https://github.com/choderalab/covid-moonshot-ml/commit/7e97f76fae1ed6867ec07b09bb8cc4f484a99ac9

**Comment by kaminow** [comment]
>     * is path-based I/O ok or is another way desired? If so please point me to an example

I think file-base is good for the SMARTS string, but in my mind the compound input would be taken as a list of `ExperimentalCompoundData` objects, so that one experimental input file could be used for multiple docking runs, by just changing the SMARTS input file.

>     * where would you like this function implemented?

I think for now `datasets.utils` makes sense, as this is where other similar functions are currently located.

>     * is there need for the inverse function as well? i.e. if query SMARTS is found, remove the cpd from docking input?

maybe this could be implemented as a boolean input argument to the function (i.e. blacklist vs whitelist)

>     * I wasn't sure what the hashtags represent in @jchodera's [SMARTS queries file example](https://github.com/FoldingAtHome/covid-moonshot/blob/master/synthetic-enumeration/sprint-12/annotations/annotations.csv) represented but I'm assuming they're used to enable/disable filters. With the hashtags SMARTS parsing by OE fails of course, so I set a flag to either ignore the commented SMARTS entries or to include all of them by removing the hashtag.

I think you're right, and the way you're handling it sounds good to me!

**Comment by JenkeScheen** [comment]
an early prototype of this code has been merged into `allucinate_fragalysis`; waiting to finalise until https://github.com/choderalab/covid-moonshot-ml/pull/39 is done. Keeping the issue open for now, though

**Comment by apayne97** [comment]
Building on @JenkeScheen 's code in this PR here: https://github.com/choderalab/covid-moonshot-ml/pull/56
