### ISSUE TITLE
Fix dimer alignment

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#60]
# Intro
Although alignment seems to have worked for monomer systems, for dimers there are stochastic errors.

### The api to run this is here:
https://github.com/choderalab/covid-moonshot-ml/blob/add-seqres-protein-prep/covid_moonshot_ml/modeling.py#L264

### And a script to run this protein prep is here:
https://github.com/choderalab/covid-moonshot-ml/blob/add-seqres-protein-prep/scripts/prep_proteins.py

## Related to these issues:
- #34 
- #47
- #61 

## And this PR:
- #58

# ToDo
- [x] ascertain when/how it is failing
- [x] implement a fix!

# Examples:
`posit_hybrid_no_relax_keep_water_filter/ALP-POS-ecbed2ba-12_0A/dimer/rcsb_4RSP_B`
![image](https://user-images.githubusercontent.com/31800806/193600669-70a0900c-d63a-4f0c-9afa-e6282a62f755.png)

**Comment by apayne97** [comment]
Here is a list of the alignments where chain B looks like this:
![image](https://user-images.githubusercontent.com/31800806/193604455-e13daf77-70ce-44b0-adfa-67d38e215971.png)
- 4RSP
- 5WKJ
- 5WKK
- 5WKL
- 5WKM
- 7T40
- 7T41
- 7TQ7
- 7TQ8
- 8CZT
- 8CZU
- 8CZV
- 8DGY

**Comment by kaminow** [comment]
thanks for catching this! I'm looking into it, I'll be working in the `bug-60-dimer-alignment` branch

**Comment by apayne97** [comment]
I just checked - all of these PDBs only have a single chain anyway, so we just need a way to catch that before trying to run the alignment.

**Comment by apayne97** [comment]
When you're ready do you want to add a PR from that branch to https://github.com/choderalab/covid-moonshot-ml/tree/add-seqres-protein-prep? That way we can add all the protein-prep related stuff at once?
