### ISSUE TITLE
Enable writing out CONECT records from OpenEye objects

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#66]
*sigh* For some reason it doesn't look like the CONECT records are getting written out for HETATMs, even though I think the default behaviour is that they should be getting written out.

https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEIFlavor.html?highlight=flavor#OEChem::OEIFlavor::PDB

> DEFAULT
> 
> Combination of [OEOFlavor_PDB_OrderAtoms](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEOFlavor.html?highlight=oeoflavor_pdb_default#OEChem::OEOFlavor::PDB::OrderAtoms), [OEOFlavor_PDB_OEResidues](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEOFlavor.html?highlight=oeoflavor_pdb_default#OEChem::OEOFlavor::PDB::OEResidues), [OEOFlavor_PDB_HETBONDS](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEOFlavor.html?highlight=oeoflavor_pdb_default#OEChem::OEOFlavor::PDB::HETBONDS), [OEOFlavor_PDB_ELEMENT](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEOFlavor.html?highlight=oeoflavor_pdb_default#OEChem::OEOFlavor::PDB::ELEMENT) and [OEOFlavor_PDB_BOTH](https://docs.eyesopen.com/toolkits/python/oechemtk/OEChemConstants/OEOFlavor.html?highlight=oeoflavor_pdb_default#OEChem::OEOFlavor::PDB::BOTH) flags.

**Comment by jchodera** [comment]
In the `_bound.pdb` files, the ligand is also not being written out as `HETATM`s, but as `ATOM`.

**Comment by apayne97** [comment]
I would like to solve both of these problems but OpenEye is confusing:

This is what we had before:
```
ATOM      1  C   UNL     1       3.197   2.360  20.796  0.00  0.00           C
ATOM      2  C   UNL     1       3.913   1.877  21.882  0.00  0.00           C
ATOM      3  C   UNL     1       3.573   2.049  19.519  0.00  0.00           C
ATOM      4  C   UNL     1       5.023   1.099  21.696  0.00  0.00           C
```

If I add this code we get this:
```
        for atom in lig.GetAtoms():
            residue = oechem.OEAtomGetResidue(atom)
            residue.SetChainID("L")
            residue.SetName("LIG")
            residue.SetHetAtom(True)
            oechem.OEAtomSetResidue(atom, residue)
```

```
HETATM    0  C   LIG L   1       3.197   2.360  20.796  1.00 20.00           C
HETATM    0  C   LIG L   1       3.913   1.877  21.882  1.00 20.00           C
HETATM    0  C   LIG L   1       3.573   2.049  19.519  1.00 20.00           C
```
Which is good except that now the atoms are all labeled with index 0 and I don't get any connect records.

Now for the annoying part, if I keep only the SetHetAtom(True) line, with still the `oechem.OEOFlavor_PDB_DEFAULT` set as the flavor:
```
for atom in lig.GetAtoms():
      residue = oechem.OEAtomGetResidue(atom)
      # residue.SetChainID("L")
      # residue.SetName("LIG")
      residue.SetHetAtom(True)
      # oechem.OEAtomSetResidue(atom, residue)
```
ATOM      1  C   UNL     1       3.197   2.360  20.796  0.00  0.00           C
ATOM      2  C   UNL     1       3.913   1.877  21.882  0.00  0.00           C
ATOM      3  C   UNL     1       3.573   2.049  19.519  0.00  0.00           C
.
.
.
CONECT    1    2    3   35
CONECT    2    1    4   36
CONECT    3    1   10   37
CONECT    4    2   11   38
```

**Comment by jchodera** [comment]
You can renumber atoms while preserving residue numbers, chain IDs, and residue names like this:
```python
# Clean up PDB info after adding missing atoms
oechem.OEPerceiveResidues(mol, oechem.OEPreserveResInfo_ChainID | oechem.OEPreserveResInfo_ResidueNumber | oechem.OEPreserveResInfo_ResidueName)
```
