### ISSUE TITLE
Rename docked molecule to LIG to be consistent with fragalysis

### ISSUE THREAD

**Issue by jchodera** [choderalab/covid-moonshot-ml#73]
Currently, docked molecules are named residue `UNL`, but it would be better to rename them to `LIG` to be consistent with fragalysis.

**Comment by jchodera** [comment]
The chain ID also appears to be blank. We may need to do something about associating the chain ID with the subunit we are docking to.

**Comment by apayne97** [comment]
Would you rather have it be in the same chain as the identified binding site or have it be in its own chain? I think we're putting it in chain L right now

**Comment by apayne97** [comment]
this is currently done in `asapdiscovery.data.openeye.save_openeye_design_unit`
