### ISSUE TITLE
Grab-bag of issues from 20k docking attempt

### ISSUE THREAD

**Issue by apayne97** [choderalab/covid-moonshot-ml#76]
# Intro
We tried to make a bunch of molecules for a 40k molecule enumeration, and we hit a variety of snags and I wanted to have a single place to keep track of the challenges we experienced. I've put them in 3 categories, with the hope that while Ben and I are happy to work on (1) and maybe parts of (2), we'd like to mostly hand off (3) to other people who are better qualified to make improvements there!

# 1) Science Issues
Issues related to the validity and meaning of the results we have generated.

- [x] why are we stochastically docking to chain A vs chain B when the crystal ligand exists in both chains? i.e. `20k_filtered_frag_docked_full_posit_best_amp_20221019/2955_Mpro-P2036_0/2955_Mpro-P2036_0_bound.pdb`
- [x] why did we fail to build in loops for at least some of the systems? i.e. `20k_filtered_frag_prepped_dus/Mpro-P2036_0A_ALP-POS-1cbc2fae-1/prepped_complex.pdb`
- [x] need to add a way to filter the "best results" by chemgauss score as well

# 2) Code Database frustration
Issues related to using (and re-using) the code we're written.
- [x] update the `collate_results.py` script by adding input arguments and put in the `scripts` folder of the repo
- [x] make standard names for `results.csv` columns instead of creating them in lists in scripts and make functions that process them intelligently
- [x] this is a thing that involves all three categories: `fauxalysis_from_docking.py` is now quite slow and may not be doing a useful thing (see the first issue in (3). at minimum it should be rewritten to do some multiprocessing to prepare structures. the simplest thing that can be improved is getting a list of sdf files to concatenate to make a combined.sdf first before copying over all the files.

# 3) Downstream processing issues
Issues related #75, and also passing off the results to Med Chemists via postera.ai, etc.
- [x] how should we visualize the docking results? generating a complex pdb file for every docked result is quite a lot of data

**Comment by JenkeScheen** [comment]
Thanks Alex - two initial comments:
- regarding the docking to chain A/B: we might get lucky here, it looks like we can pass a `chain_id` parameter to `kinoml` [when setting up the docking](https://github.com/choderalab/covid-moonshot-ml/blob/main/covid_moonshot_ml/docking/docking.py#L128) in `covid-moonshot-ml`. See the [original class in `kinoml`: `OEDockingFeaturizer()`](https://github.com/openkinome/kinoml/blob/master/kinoml/features/complexes.py#L1327)

- I've been chatting with the Postera folks - one bottleneck on their side is that if we want to upload large CSVs with docking results to their webserver _we have to minimise the number of columns_ for server capacity reasons. So: we should take care to remove columns once we know which are redundant.

**Comment by JenkeScheen** [comment]
another issue that I ran into today:

Because we've docked the 40K series in a way where each compound is docked against 10 reference structures the output data spans across several hundreds of MPro structures. I wrote some prototype code that wrangles all the docking outputs and creates a folder for each MPro structure as well as the corresponding `.csv` and `.sdf` data for easier viewing by medchemists:
```
├── complete CSV file
├── complete multi-SDF      
├── Mpro structure 1   
│   ├── CSV file with matched docking outputs     
│   ├── Multi-SDF with ligands matched with CSV          
│   ├── Mpro reference PDB     
├── Mpro structure n
│   ├ ...
```

However, because of the docking design we end up having several hundreds of these folders. Sifting through 200-500 ligand poses and discarding some is doable for humans, but having these spread across several hundreds of folders makes the task too expensive I think.

I guess the ideal situation would be having a single PDB structure and flipping through the complete set of hit ligands, but currently there is no way to do this?

**Comment by apayne97** [comment]
I think this is a question for the med chemists. I think the options are:
1) Do what you've done so far, splitting it up by structure and having the annoyance.
2) Be able to flip through all ligands at once using a single pdb structure, with the caveat that the single pdb structure will be incorrect for many of the ligands. 
3) Load all `_bound.pdb` models at once (could probably somehow write out as a multi-model pdb) so that as you click through the compounds you are also clicking through the relevant pdb structures. This means that the output directory is larger (because you've separately saved multiple copies of the reference pdb structure)
